/*
 * generated by Xtext 2.12.0-SNAPSHOT
 */
package io.typefox.xtext.langserver.example.ide


/**
 * Use this class to register ide components.
 */
class MyDslIdeModule extends AbstractMyDslIdeModule {
}
